---
# Packages

# Install packages
- name: Install general packages
  become: true
  pacman:
    name: "{{ packages_setup }}"

- name: Install & configure GUI
  pacman:
    name: "{{ packages_gui }}"
  notify: Enable & start sddm
  when: enable_gui
