---
# Packages

# Install packages
- name: Install general packages
  become: true
  pacman:
    name: "{{ packages_setup }}"

- name: Install & configure GUI
  become: true
  pacman:
    name: "{{ packages_gui }}"
  notify: Restart sddm
  when: enable_gui
